import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Image from "next/image";
const montserrat = Unbounded({ subsets: ["latin", 'cyrillic', 'cyrillic-ext'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className + ' bg-black dark relative'}>
        <div className="">
          <Header />
          <div className="w-full max-w-6xl px-2 mx-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
