import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import ContextProvider from "../components/ui/providers";
import dynamic from "next/dynamic";
import ScrollTest from "@/components/ui/scrollProgress";
const Mouse = dynamic(() => import("@/components/ui/Mouse"), { ssr: false });
const montserrat = Unbounded({
  subsets: ["latin", "cyrillic", "cyrillic-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={
          montserrat.className + " group/body dark relative bg-black text-white"
        }
        style={{ background: "black" }}
      >
        <ContextProvider>
          <ScrollTest />
          <Header />
          <Mouse />
          <div className="mx-auto w-full max-w-6xl px-2 py-1">{children}</div>
        </ContextProvider>
      </body>
    </html>
  );
}
