import type { Metadata } from "next";
import { Unbounded } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
const montserrat = Unbounded({
  subsets: ["latin", "cyrillic", "cyrillic-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className + " dark relative bg-black"}>
        <div className="">
          <Header />
          <div className="mx-auto w-full max-w-6xl px-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
